[package]
name = "meshview"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
kiss3d = "0.27.0"
nalgebra = "0.23.0"

#[patch.crates-io]
#kiss3d = { path = "../kiss3d" }
